### ISSUE TITLE
Walkthrough Document: Conditional Transitions has unsupported syntax

### ISSUE THREAD

**Issue by jalfvort** [vorteil/direktiv#1]
**Describe the bug**
In the walkthrough document: https://github.com/vorteil/direktiv/blob/e86604f/specification/walkthrough/04_conditional-transitions.md , there is a Foreach State example. This example has a foreach state that iterates over `array: '{ .names }'`. However at this moment, this syntax `{.names}` is not a supported iterable. 

This issue can be fixed by simply changing what array iterates over to `.names[] | { name: . }`, but this probably needs some additional explanation/context in the documents.

**To Reproduce**
Just run this workflow:
```yaml
id: multiposter
functions:
- id: httprequest
  image: vorteil/request
states:
- id: poster
  type: foreach
  array: ".names[] | { name: . }"
  action:
    function: httprequest
    input: '{
      "method": "POST",
      "url": "https://jsonplaceholder.typicode.com/posts",
      "body": {
        "name": .name	
      }
    }'
  transform: 'del(.names) | .names = []'

```

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS8.1
