### ISSUE TITLE
Getting "command produced a non-object output" when substituting args in error state.

### ISSUE THREAD

**Issue by jalfvort** [vorteil/direktiv#141]
**Describe the bug**
When substituting non-object error args to a error message the error state will have the jq error: `direktiv.jq.notObject - the ``jq`` command produced a non-object output`.

**To Reproduce**
Create this workflow and run it
```yaml
id: hello
description: ""
states:
  - id: helloworld
    type: noop
    transition: print-error
    transform: 'jq({ errorMsg: "Hello world!" })'
  - id: print-error
    type: error
    error: validation.error
    message: "error message was: %s"
    args:
    - jq(.errorMsg)
 ```
You should get `Workflow Error: direktiv.jq.notObject - the ``jq`` command produced a non-object output`

**Expected behavior**
I expect to get `Workflow Error: validation.error - error message was: Hello world!`
