### ISSUE TITLE
API: wait query when executing a workflow hangs during a subflow when original workflow was error.

### ISSUE THREAD

**Issue by jalfvort** [vorteil/direktiv#150]
**Describe the bug**
When executing a workflow using the api with the query ?wait=true. If the workflow I'm executing ends with a subflow the POST request never returns. This only happens if an error state was called before subflow in the original workflow.

**To Reproduce**
You can reproduce by running the `error` workflow below:
```yaml
id: error
description: ""
states:
  - id: error-out-of-date
    type: error
    error: validation.outOfDate
    transition: subflow-cleanup
    message: "this is a broken workflow"
  - id: subflow-cleanup
    type: action
    action:
      workflow: cleanup
      input: 'jq({message: "clean done"})'
```

```yaml
id: cleanup
description: ""
states:
  - id: cleanup
    type: noop
    transform: 'jq({ result: . })'
```
