### ISSUE TITLE
File being overwritten when defined twice in function files

### ISSUE THREAD

**Issue by jalfvort** [vorteil/direktiv#180]
If I define an isolated function with two files with the same key in different scopes it will only write the last one.

Example below will write the workflow hello var to direktiv-data/vars/hello
```yaml
- type: isolated
  id: request-isolate
  image: localhost:5000/isolate-echo
  files:
    - key: hello
      scope: namespace
      type: plain
    - key: hello
      scope: workflow
      type: plain
```

**Comment by alankm** [comment]
The `as` field was created to allow for renaming variables when they're written to the disk. i.e.

```yaml
- type: isolated
  id: request-isolate
  image: localhost:5000/isolate-echo
  files:
    - key: hello
      scope: namespace
      type: plain
      as: nshello
    - key: hello
      scope: workflow
      type: plain
      as: wfhello
```

Having two variables with the same name without renaming either is a bug. I'll make a change to catch the error so that it doesn't pass by silently.
