### ISSUE TITLE
Referencing a function that has not been defined fails unhelpfully.

### ISSUE THREAD

**Issue by jamesjmurtagh** [vorteil/direktiv#2]
If I have a state using function `myaction` in a workflow that does NOT include the function definition, the workflow (understandably) fails but the resulting logs are not helpful.

Good YAML:

```yaml
id: request
description: "Get a dad joke from the net." 
functions:
- id: myaction
  image: vorteil/request
states:
- id: myrequest
  type: action
  action:
    function: myaction
    input: '{
      "method" : "GET",
      "url"    : "https://icanhazdadjoke.com/",
      "headers": {
        "Accept": "application/json"
      }
    }'
```

Bad YAML:

```yaml
id: request
description: "Get a dad joke from the net." 
states:
- id: myrequest
  type: action
  action:
    function: myaction
    input: '{
      "method" : "GET",
      "url"    : "https://icanhazdadjoke.com/",
      "headers": {
        "Accept": "application/json"
      }
    }'
```

Logs:

```
[9:33:14] Beginning workflow triggered by API.
[9:33:14] Running state logic -- myrequest:1 (action)
[9:33:14] Workflow crashed due to an internal error.
```
