### ISSUE TITLE
Transitions in eventXor states

### ISSUE THREAD

**Issue by jensg-st** [vorteil/direktiv#203]
**Is your feature request related to a problem? Please describe.**

eventXor states can not transition based on the event coming in. In many cases that requires an additional switch state after the xor state. In this switch state the event can be jq'd.

```yaml
  - id: wait-for-order
    type: eventXor
    timeout: PT1M
    events:
      - event:
          type: io.direktiv.order.cancel
      - event:
          type: io.direktiv.order.done
```

**Describe the solution you'd like**

It should be possible to route based on the event coming int like this:

```yaml
  - id: wait-for-order
    type: eventXor
    timeout: PT1M
    events:
      - event:
          type: io.direktiv.order.cancel
         transition: cancel-state
      - event:
          type: io.direktiv.order.done
          transition: done-state
```
