### ISSUE TITLE
Executing an action with an Image doesnt exist hangs.

### ISSUE THREAD

**Issue by trentis** [vorteil/direktiv#26]
**Describe the bug**
Executing an action where an image does not exists results in it pending forever.

**To Reproduce**
Run

```yaml
id: req2
functions:
  - id: httprequest
    image: vorteil/request5:v1
states:
  - id: getter
    type: action
    action:
      function: httprequest
      input: '{ "method": "GET", "url": "https://www.example.com/", }'
```
**Expected behavior**
An error telling me the image I am trying to get doesn't exist.
