### ISSUE TITLE
Wildcard error catch not working correctly on validate state

### ISSUE THREAD

**Issue by jalfvort** [vorteil/direktiv#3]
**Describe the bug**
Running a workflow validate state that fails will not be caught by a wildcard error code. 
Example below:

**This workflow does not catch the schema error:**
```yaml
id: zzzz
states:
- id: validateInput
  type: validate
  schema:
    type: object
    required:
    - contact
    - payload
    additionalProperties: false
    properties:
      contact:
        type: string 
      payload:
        type: string
  catch:
  - error: "*"
    transition: bad-input
  transition: notify
- id: notify
  type: noop
  transform: '{ result: "Hello World!" }'
- id: bad-input
  type: noop
  transform: '{ error: "Please input contact and payload" }'
```

**This workflow does catch the error:**
```yaml
id: zzzz
states:
- id: validateInput
  type: validate
  schema:
    type: object
    required:
    - contact
    - payload
    additionalProperties: false
    properties:
      contact:
        type: string 
      payload:
        type: string
  catch:
  - error: "direktiv.schema.failed"
    transition: bad-input
  transition: notify
- id: notify
  type: noop
  transform: '{ result: "Hello World!" }'
- id: bad-input
  type: noop
  transform: '{ error: "Please input contact and payload" }'
```

The only difference is one error is using the wildcard, and the other one is using a specific error code.
```
  catch:                            catch:
  - error: "*"                →     - error: "direktiv.schema.failed"
    transition: bad-input             transition: bad-input
```
