### ISSUE TITLE
YAML with incorrectly indented catch statement is accepted as valid. 

### ISSUE THREAD

**Issue by jamesjmurtagh** [vorteil/direktiv#6]
### Problem description

No issue was reported with YAML that had a catch defined in the action level instead of the state level of a workflow definition.

#### Incorrect YAML

```yaml
id: errors-and-retries
description: "This workflow is designed to fail, have its' error caught, and 'retry' 3 times." 
functions:
- id: failpredictably
  image: ghouljim/throwerror:latest
states:
- id: hello
  type: action
  action:
    function: failpredictably
    input: '{}'
    catch:
    - error: 'error.mustfail'
      retry:
        maxAttempts: 3
        delay: PT30S
        multipler: 2.0
````

#### Correct YAML

```yaml
id: errors-and-retries
description: "This workflow is designed to fail, have its' error caught, and 'retry' 3 times." 
functions:
- id: failpredictably
  image: ghouljim/throwerror:latest
states:
- id: hello
  type: action
  action:
    function: failpredictably
    input: '{}'
  catch:
  - error: 'error.mustfail'
    retry:
      maxAttempts: 3
      delay: PT30S
      multipler: 2.0
```
      
### Expected behaviour

This should be reported as invalid YAML because the catch is incorrectly indented.

### Actual behaviour

The YAML is accepted as valid. Caused a few minutes of confusion when I noticed that exact error not being caught.
