### ISSUE TITLE
eventAndState and generateEventState

### ISSUE THREAD

**Issue by trentis** [vorteil/direktiv#8]
**Describe the bug**
Running a eventAnd state and generating events using the generateEventState triggers an error saying id, type and source is not there.

**To Reproduce**
1. Run
```yaml
id: event-and
description: "" 
states:
- id: hello
  type: eventAnd
  events: 
  - event:
     type: cloudevent
  - event:
     type: cloudevent2
```
2. Then run
```yaml
id: generate-event
description: "generates a test.cloud event" 
states:
- id: generate
  type: generateEvent
  event:
    type: cloudevent
    source: cloudevent
    datacontenttype: "application/json"
  transition: gen2
- id: gen2
  type: generateEvent
  event:
    type: cloudevent2
    source: cloudevent2
```
4. Check logs of pipeline for eventAnd state

**Expected behavior**
The eventAnd state workflow should complete successfully
